[package]
name = "sabi"
version = "0.1.0"
authors = ["ChangedUser <zivojinovic.ma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "*"
serde = "1.0.106"
colored = "1.9.3"
structopt = "0.3.14"
